apiVersion: v2
appVersion: "1.0"
description: A Helm chart for platops-ai App
name: platops-platops-ai
home: https://github.com/hmcts/platops-ai
version: 0.0.9
maintainers:
  - name: HMCTS platops team
dependencies:
  - name: java
    version: 4.2.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
